SET NAMES utf8mb4 COLLATE utf8mb4_0900_ai_ci;

INSERT INTO house_info (
    source_record_id,
    title,
    city,
    district,
    community,
    address,
    total_price,
    unit_price,
    area,
    bedroom_count,
    living_room_count,
    layout,
    orientation,
    floor_description,
    floor_level,
    total_floors,
    decoration,
    listing_date,
    data_source
) VALUES (
    'SAMPLE-001',
    '阳光花园三室两厅',
    '上海市',
    '浦东新区',
    '阳光花园',
    '示例路1号',
    500.00,
    50000.00,
    100.00,
    3,
    2,
    '3室2厅',
    'MULTIPLE',
    '中楼层/共18层',
    'MIDDLE',
    18,
    'REFINED',
    '2026-01-01',
    'PUBLIC_DATASET'
) AS new
ON DUPLICATE KEY UPDATE
    title = new.title,
    city = new.city,
    district = new.district,
    community = new.community,
    address = new.address,
    total_price = new.total_price,
    unit_price = new.unit_price,
    area = new.area,
    bedroom_count = new.bedroom_count,
    living_room_count = new.living_room_count,
    layout = new.layout,
    orientation = new.orientation,
    floor_description = new.floor_description,
    floor_level = new.floor_level,
    total_floors = new.total_floors,
    decoration = new.decoration,
    listing_date = new.listing_date;
